Repository devind-team/graphene-django-filter, pull requests merged in 2022-02, with the labels that each got.

#1 Basic functionality
  .flake8
  .pre-commit-config.yaml
  README.md
  graphene_django_filter/__init__.py
  graphene_django_filter/connection_field.py
  graphene_django_filter/filterset.py
  graphene_django_filter/filterset_factories.py
  graphene_django_filter/input_type_factories.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/connection_field.py
  tests/data_generation.py
  tests/filtersets.py
  tests/models.py
  tests/object_types.py
  tests/schema.py
  tests/settings.py
  tests/test_connection_field.py
  tests/test_filterset.py
  tests/test_input_type_factories.py
  whitelist.txt
Labels: enhancement

#2 Hot fix
  .github/workflows/ci.yml
Labels: bug

#6 The `not` operator
  .flake8
  README.md
  graphene_django_filter/filterset.py
  graphene_django_filter/input_type_factories.py
  poetry.lock
  pyproject.toml
  tests/filtersets.py
  tests/object_types.py
  tests/test_connection_field.py
  tests/test_filterset.py
  tests/test_input_type_factories.py
Labels: enhancement

#8 chore: Added description file for dependabot
  .github/dependabot.yml
Labels: enhancement

#14 fix: Update django dependency and add how to install information #13
  README.md
  pyproject.toml
Labels: documentation, dependencies
